# -*- coding: utf-8 -*-
"""E-commerce Purchase Analysis (NumPy | Pandas | Matplotlib | Seaborn).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAaBrtB_DNlwvkBd9QQXCDrg3UJHnnsY

Dataset - https://www.kaggle.com/datasets/utkarsharya/ecommerce-purchases
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv("/content/drive/MyDrive/Datasets/Ecommerce Purchases")

"""## Display Top 10 rows of the dataset"""

data.head(5)

"""## Display Last 10 rows of the dataset"""

data.tail(5)

"""Check datatype of each column"""

data.dtypes

"""## Check null values in the dataset"""

data.isnull().sum()

"""## How many rows and columns are there in our dataset"""

data.columns

len(data.columns)

len(data)

data.info()

"""## Highest and Lowest Purchases"""

highest = data['Purchase Price'].max()
print(highest)

lowest = data['Purchase Price'].min()
print(lowest)

"""## Average Purchase Prize"""

avg_purchase_prize =data['Purchase Price'].mean()
print(avg_purchase_prize)

"""## How many people have french 'fr' as their language?

"""

len( data[data['Language']== "fr"])

data[data['Language']== "fr"].count()

"""## Job Title Contains Engineer"""

data[data['Job'].str.contains("engineer" , case= False)]

"""## Find the email of the person with the following ip address: 132.207.106.22"""

data[data['IP Address']=="132.207.160.22"]

data[data['IP Address']=="132.207.160.22"]['Email']

"""## How many people have Mastercard as their credit card provider and made purchase above 50 ?"""

data[(data['CC Provider']=="Mastercard" ) & (data['Purchase Price']>50 ) ]

len(data[(data['CC Provider']=="Mastercard" ) & (data['Purchase Price']>50 ) ])

data[(data['CC Provider']=="Mastercard" ) & (data['Purchase Price']>50 ) ].count()

""" ## Find Email of the person with the following Credit Card Number: 4664825258997302"""

data[data['Credit Card']==4664825258997302]['Email']

"""## How many people purchase during the AM and how many people purchase during the PM"""

len(data[data['AM or PM']=="AM"])

len(data[data['AM or PM']=="PM"])

data['AM or PM'].value_counts()

"""## How many people have a credit that expires in 2020"""

exp_2020 = data[data['CC Exp Date'].str[-2:] == '20']
exp_2020

count_2020 = exp_2020.shape[0]
count_2020

def func():
  c=0
  for date in data['CC Exp Date']:
    if date.split('/')[1]=='20':
      c+=1
  return c
func()

len(data[data['CC Exp Date'].apply(lambda x:x[3:]=="20")])

"""## Top 5 most popular email providers (eg. gmail.com, yahoo.com, etc...)"""

data['Email'].str.split('@')

l=data['Email'].apply(lambda x:x.split('@')[1]).value_counts().head()
l

"""##  E‑Commerce Purchases by Time of Day (AM vs PM)"""

ampm = data['AM or PM'].value_counts()
ampm

sns.countplot(x='AM or PM', data=data, palette='Set2' ,   hue='AM or PM')
plt.title("Purchases: AM vs PM")
plt.show()

"""### Top Professions Among E‑Commerce Customers"""

lang = data['Job'].value_counts().head(3)

plt.figure(figsize=(6,5))
plt.pie(lang, labels=lang.index, autopct='%1.1f%%')
plt.title('Job Distribution')
plt.show()

"""## Total Credit card expiry in next 3 years"""

exp_24 =len(data[data['CC Exp Date'].apply(lambda x:x[3:]=="24")])
exp_25 =len(data[data['CC Exp Date'].apply(lambda x:x[3:]=="25")])
exp_26 =len(data[data['CC Exp Date'].apply(lambda x:x[3:]=="26")])
print(exp_24,exp_25,exp_26)

years = ['2024', '2025', '2026']
values = [exp_24, exp_25, exp_26]

plt.figure(figsize=(5,3))
plt.bar(years, values, color='skyblue', width=0.5)

plt.title('C', fontsize=12)
plt.xlabel('Expiry Year', fontsize=10)
plt.ylabel('Count', fontsize=10)

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(12,4))

ax = sns.countplot(
    y='CC Provider',
    data=data,
    order=data['CC Provider'].value_counts().index[:5],
    hue='CC Provider',        # required when using palette
    palette='pastel',
    legend=False              # hide legend
)

plt.title("Top 10 Credit Card Providers")
plt.xlabel("Count")
plt.ylabel("Credit Card Provider")
plt.show()

"""### Numpy - High-Value Customers

"""

print(np.mean(data['Purchase Price']))

import numpy as np
high_spenders = data[data['Purchase Price'] > np.mean(data['Purchase Price'])]
print("High value transactions:", len(high_spenders))

"""### Helps detect unusually high purchase values."""

prices = data['Purchase Price'].values
z_scores = (prices - np.mean(prices)) / np.std(prices)

outliers = prices[np.abs(z_scores) > 3]
print("Outliers detected:", len(outliers))

